# Generated by Django 4.2.4 on 2024-01-29 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('make_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='', upload_to='pic')),
                ('ser_name', models.CharField(default='', max_length=30)),
                ('description', models.CharField(default='', max_length=250)),
                ('price', models.FloatField()),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_by_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
