# Generated by Django 4.2.4 on 2024-01-31 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('make_service', '0003_service_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='service_booking',
        ),
    ]
