# Generated by Django 4.2.4 on 2024-01-31 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('make_service', '0004_delete_service_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='service_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(default='', max_length=25)),
                ('email', models.EmailField(default='', max_length=30)),
                ('company', models.CharField(default='', max_length=250)),
                ('model', models.CharField(default='', max_length=250)),
                ('km_done', models.FloatField()),
                ('date', models.DateTimeField()),
                ('type', models.CharField(default='', max_length=25)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_book', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
