# Generated by Django 4.2.4 on 2024-01-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_service', '0005_service_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service_booking',
            name='ownername',
            field=models.CharField(default='', max_length=25, null=True),
        ),
    ]
