# Generated by Django 4.2.4 on 2024-02-04 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_service', '0007_service_booking_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='service_booking',
            name='car_services',
            field=models.ManyToManyField(related_name='service_bookings', to='make_service.carservice'),
        ),
    ]
