# Generated by Django 4.2.4 on 2024-02-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_service', '0008_carservice_service_booking_car_services'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service_booking',
            name='email',
        ),
        migrations.AddField(
            model_name='service_booking',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
