# Generated by Django 4.2.4 on 2024-02-06 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('make_service', '0009_remove_service_booking_email_service_booking_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_service',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='make_service.service_station'),
        ),
    ]
