# Generated by Django 4.2.4 on 2024-02-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_service', '0010_add_service_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_service',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
