# Generated by Django 4.2.4 on 2024-02-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('make_service', '0011_add_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_booking',
            name='vehno',
            field=models.CharField(default='', max_length=250),
        ),
    ]
