# Generated by Django 4.2.4 on 2024-02-07 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('make_service', '0013_service_booking_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service_booking',
            old_name='delete',
            new_name='deletee',
        ),
    ]
